backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "donnees"
    label: "Données du site"
    files:
      - file: "plat.json"
        label: "Plat du Jour"
        name: "plat"
        fields:
          - {label: "Nom du Plat", name: "plat_du_jour", widget: "string"}
          - {label: "Prix", name: "prix_plat_jour", widget: "string"}