backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "donnees"
    label: "Données du site"
    files:
      - file: "plat.json"
        label: "La Carte"
        name: "carte"
        fields:
          - {label: "Nom du Plat du Jour", name: "plat_du_jour", widget: "string"}
          - {label: "Prix Plat du Jour", name: "prix_plat_jour", widget: "string"}
          - {label: "Les Entrées", name: "entrees", widget: "text", hint: "Séparez par un retour à la ligne"}
          - {label: "Les Plats", name: "plats", widget: "text", hint: "Séparez par un retour à la ligne"}
          - {label: "Les Desserts", name: "desserts", widget: "text", hint: "Séparez par un retour à la ligne"}